name: Deploy to GitHub Pages Speed-X

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for last_modified

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Metadata
        run: |
          npm install
          node generate_metadata.js
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add files_metadata.json files_metadata.json.gz
          git commit -m "Auto-update metadata [skip ci]" || echo "No changes to commit"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
